#include "libft.h"

int	main(int argc, char **argv)
{
	char	str_memset[50];
	char	str_bzero[50];
	char	src_memcpy[50] = "it work if u see it";
	char	dest_memcpy[50];
	char	src_memccpy[50] = "idk what im doing";
	char	dest_memccpy[50];
	char	s1_memmove[50] = "oldstring";
	char	s2_memmove[50] = "newstring";
	char	s1_memchr[50] = "im a string with a hiden character z";
	char	to_find = 'x';
	char	s1_memcmp[50] = "abcdefghijklmnopqrstuvwxyz";
	char	s2_memcmp[50] = "zyxw";
	char	s3_memcmp[50] = "123";
	char	s4_memcmp[50] = "987";
	char	s5_memcmp[50] = "9";
	char	s6_memcmp[50] = "9";
	char	s1_strlen[50] = "bonjour je suis uen chaine de caracteres";
	char	s2_strlen[50] = "5354";
	char	s3_strlen[50] = "";
	char	s4_strlen[50] = "p";
	char	s1_strdup[50] = "bondour bondour";
	char	s2_strdup[50] = "oni chan yamero";
	char	dest_strcpy[50] = "bla bla bla";
	char	dest2_strcpy[50] = "blo blo blo";
	char	dest3_strcpy[50] = "bli bli bli";
	char	dest4_strcpy[50] = "bl bl bl bl";
	char	src_strcpy[50] = "je suis une phrase de test";
	char	src2_strcpy[50] = "im a string to test strcpy";
	char	src3_strcpy[50] = "bla bla bla 12039487";
	char	src4_strcpy[50] = "popadddaodmzpzowjeqwer";
	char	src_strncpy[50] = "im a string to test";
	char	src2_strncpy[50] = "some shit to write";
	char	dest_strncpy[50] = "blabla bla blo";
	char	dest2_strncpy[50] = "bla bla bla";
	char	strcat_src[50] = "phrase src";
	char	strcat_dest[50] = "phrase dest.";
	char	strcat_src2[50] = "789";
	char	strcat_dest2[50] = "123456";
	char	strncat_src[50] = "phrase src";
	char	strncat_dest[50] = "phrase dest.";
	char	strncat_src2[50] = "456789";
	char	strncat_dest2[50] = "123";
	char	strlcat_src[50] = "phrase src";
	char	strlcat_dest[50] = "phrase dest.";
	char	strlcat_src2[50] = "456789";
	char	strlcat_dest2[50] = "123";
	char	str_strchr[50] = "bonjour je suis papa";
	char	str_strchr2[50] = "bqajo afejkhr ";
	char	str_strchr3[50] = "blablablaeble5blabl";
	char	str_strchr4[50] = "pppppppppppppppp963";
	char	str_strchr5[50] = "bonjour je suis une super phrase \0 idaaur";
	char	str_strrchr[50] = "bonjour je suis papa";
	char	str_strrchr2[50] = "bqajo afejkhr ";
	char	str_strrchr3[50] = "blablablaeble5blabl";
	char	str_strrchr4[50] = "pppppppppppppppp963";
	char	str_strrchr5[50] = "bonjour je suis une super phrase \0 idaaur";
	char	str_strstr[50] = "bonjour bonjour xxx bonjour ";
	char	str_strstr2[50] = "aaaaaaaaaaaaaaaa555";
	char	str_strstr3[50] = "669969666999";
	char	str_strstr4[50] = "ppppppppppppp";
	char	str_strstr5[50] = "bonjour je suis une super iosdgjfskphrase idaaur";
	char	str_tofind[50] = "xxx";
	char	str_tofind2[50] = "555";
	char	str_tofind3[50] = "666";
	char	str_tofind4[50] = "ddd";
	char	str_tofind5[50] = "xxxzz";
	char	s1_strncmp[50] = "je suis une chaine de caracteres";
	char	s2_strncmp[50] = "je suis une chaine de caracteres";
	char	s3_strncmp[50] = "hello";
	char	s4_strncmp[50] = "les";
	char	s5_strncmp[50] = "123";
	char	s6_strncmp[50] = "12";
	char	atoi_str[50] = "213";
	char	atoi_str1[50] = "123q123";
	char	atoi_str2[50] = "12 2";
	char	atoi_str3[50] = "    \t \t \r \t \n \f 123";
	char	atoi_str4[50] = "[][][][] 1 [][][][]";
	char	atoi_str5[50] = "\n \t \f \r \n 123";
	char	atoi_str6[50] = "1  1 1 1 1 11 ";
	int	is_alpha = 'a';
	int	is_alpha2 = '1';
	int	is_digit = '5';
	int	is_digit2 = 'd';
	int	is_alnum = 'a';
	int	is_alnum2 = ';';
	int	is_ascii = '1';
//	char	is_ascii2 = "™";
	int	is_print = '9';
//	char	is_print2 = "™";
// test memalloc
// test memdel
// test strnew

	
	
	
	
	//	if (argc == 0)
//		return (0);
/*	printf("%s\n", "ft_memset ---------------------------------");
	strcpy(str_memset,"je suis une chaine de caracteres de memset");
	puts(str_memset);
	ft_memset(str_memset, '#', 10);
	puts(str_memset);
	printf("%s\n", "ft_bzero ----------------------------------");
	strcpy(str_bzero,"je suis une chaine de caracteres de bzero");
	puts(str_bzero);
	ft_bzero(str_bzero, 3);
	puts(str_bzero);
	printf("%s\n", "ft_memcpy ----------------------------------");
	strcpy(dest_memcpy, "test");
	printf("before ft_memcpy : %s\n", dest_memcpy);
	ft_memcpy(dest_memcpy, src_memcpy, 20);
	printf("after ft_memcpy : %s\n", dest_memcpy);
	printf("%s\n", "ft_memmove ----------------------------------");
	printf("Before memmove dest = %s, src = %s\n", s1_memmove, s2_memmove);
	ft_memmove(s1_memmove, s2_memmove, 8);
	printf("After memmove dest = %s, src = %s\n", s1_memmove, s2_memmove);
	printf("%s\n", "ft_memchr ----------------------------------");
	printf("%s\n", ft_memchr(s1_memchr, to_find, 40));
	printf(" %s\n", "ft_memcmp ----------------------------------");
	printf("mine : %d\n", ft_memcmp(s1_memcmp, s2_memcmp, 30));
	printf("mine : %d\n", ft_memcmp(s3_memcmp, s4_memcmp, 30));
	printf("mine : %d\n", ft_memcmp(s5_memcmp, s6_memcmp, 30));
	printf("%d\n", memcmp(s1_memcmp, s2_memcmp, 30));
	printf("%d\n", memcmp(s3_memcmp, s4_memcmp, 30));
	printf("%d\n", memcmp(s5_memcmp, s6_memcmp, 30));
	printf(" %s\n", "ft_strlen ----------------------------------");
	printf("mine : %zu\n", ft_strlen(s1_strlen));
	printf("mine : %zu\n", ft_strlen(s2_strlen));
	printf("mine : %zu\n", ft_strlen(s3_strlen));
	printf("mine : %zu\n", ft_strlen(s4_strlen));
	printf("%zu\n", strlen(s1_strlen));
	printf("%zu\n", strlen(s2_strlen));
	printf("%zu\n", strlen(s3_strlen));
	printf("%zu\n", strlen(s4_strlen));
	printf(" %s\n", "ft_strdup ----------------------------------");
	printf("mine : %s\n", ft_strdup(s1_strdup));
	printf("mine : %s\n", ft_strdup(s2_strdup));
	printf("%s\n", strdup(s1_strdup));
	printf("%s\n", strdup(s2_strdup));
	printf(" %s\n", "ft_strcpy ----------------------------------");
	printf("mine : %s\n", ft_strcpy(dest_strcpy, src_strcpy));	
	printf("mine : %s\n", ft_strcpy(dest2_strcpy, src2_strcpy));	
	printf("%s\n", strcpy(dest_strcpy, src_strcpy));	
	printf("%s\n", strcpy(dest2_strcpy, src2_strcpy));	
	printf(" %s\n", "ft_strncpy ----------------------------------");
	printf("mine : %s\n", ft_strncpy(dest_strcpy, src_strcpy, 10));	
	printf("mine : %s\n", ft_strncpy(dest2_strcpy, src2_strcpy, 10));	
	printf("%s\n", strncpy(dest_strcpy, src_strcpy, 10));	
	printf("%s\n", strncpy(dest2_strcpy, src2_strcpy, 10));	
	printf(" %s\n", "ft_strcat ----------------------------------");
	printf("%s\n", ft_strcat(strcat_dest, strcat_src));
	printf("%s\n", ft_strcat(strcat_dest2, strcat_src2));
	printf(" %s\n", "ft_strncat ----------------------------------");
	printf("%s\n", ft_strncat(strncat_dest, strncat_src, 3));
	printf("jai copier 3 caracteres");
	printf("%s\n", ft_strncat(strncat_dest2, strncat_src2, 3));
	printf("jai copier 3 caracteres");
	printf(" %s\n", "ft_strlcat ----------------------------------");
	printf("%zu\n", ft_strlcat(strncat_dest, strlcat_src, 10));
	printf("%zu\n", ft_strlcat(strncat_dest2, strlcat_src2, 10));
	printf(" %s\n", "ft_strchr ----------------------------------");
	printf("%s\n", ft_strchr(str_strchr, 'p'));
	printf("%s\n", ft_strchr(str_strchr2, 'o'));
	printf("%s\n", ft_strchr(str_strchr3, '5'));
	printf("%s\n", ft_strchr(str_strchr4, 'k'));
	printf("%s\n", ft_strchr(str_strchr5, '0'));
	printf(" %s\n", "ft_strrchr ----------------------------------");
	printf("%s\n", ft_strrchr(str_strchr, 'p'));
	printf("%s\n", ft_strrchr(str_strchr2, 'o'));
	printf("%s\n", ft_strrchr(str_strchr3, '5'));
	printf("%s\n", ft_strrchr(str_strchr4, 'k'));
	printf("%s\n", ft_strrchr(str_strchr5, '0'));
//	printf(" %s\n", "ft_strstr ----------------------------------");
//	printf("%s\n", strstr(str_strstr, str_tofind));
//	printf("%s\n", strstr(str_strstr2, str_tofind2));
//	printf("%s\n", strstr(str_strstr3, str_tofind3)); // erreur dans ma fonction sur ce test
//	printf("%s\n", strstr(str_strstr4, str_tofind4));
//	printf("%s\n", strstr(str_strstr5, str_tofind5));
	printf(" %s\n", "ft_strncmp ----------------------------------");
	printf("reel :%d\n", strncmp(s1_strncmp, s2_strncmp, 10));
	printf("reel :%d\n", strncmp(s3_strncmp, s4_strncmp, 10));
	printf("reel :%d\n", strncmp(s5_strncmp, s6_strncmp, 10));
	printf("mine :%d\n", ft_strncmp(s1_strncmp, s2_strncmp, 10));
	printf("mine :%d\n", ft_strncmp(s3_strncmp, s4_strncmp, 10));
	printf("mine :%d\n", ft_strncmp(s5_strncmp, s6_strncmp, 10));	
	printf(" %s\n", "ft_atoi ----------------------------------");
	printf("reel :%d\n", atoi(atoi_str));
	printf("reel :%d\n", atoi(atoi_str1));
	printf("reel :%d\n", atoi(atoi_str2));
	printf("reel :%d\n", atoi(atoi_str3));
	printf("reel :%d\n", atoi(atoi_str4));
	printf("mine :%d\n", ft_atoi(atoi_str));
	printf("mine :%d\n", ft_atoi(atoi_str1));
	printf("mine :%d\n", ft_atoi(atoi_str2));
	printf("mine :%d\n", ft_atoi(atoi_str3));
	printf("mine :%d\n", ft_atoi(atoi_str4));
*/	
	printf(" %s\n", "ft_isalpha ----------------------------------");
	printf("reel :%d\n", isalpha(is_alpha));
	printf("reel :%d\n", isalpha(is_alpha2));
	printf("mine :%d\n", ft_isalpha(is_alpha));
	printf("mine :%d\n", ft_isalpha(is_alpha2));
	printf(" %s\n", "ft_isdigit ----------------------------------");
	printf("reel :%d\n", isdigit(is_digit));
	printf("reel :%d\n", isdigit(is_digit2));
	printf("mine :%d\n", ft_isdigit(is_digit));
	printf("mine :%d\n", ft_isdigit(is_digit2));
	printf(" %s\n", "ft_isalnum ----------------------------------");
	printf("reel :%d\n", isalnum(is_alnum));
	printf("reel :%d\n", isalnum(is_alnum2));
	printf("mine :%d\n", ft_isalnum(is_alnum));
	printf("mine :%d\n", ft_isalnum(is_alnum2));
	printf(" %s\n", "ft_isascii ----------------------------------");
	printf("reel :%d\n", isascii(is_ascii));
//	printf("reel :%d\n", isascii(is_ascii2));
	printf("mine :%d\n", ft_isascii(is_ascii));
//	printf("mine :%d\n", ft_isascii(is_ascii2));
	printf(" %s\n", "ft_isprint ----------------------------------");
	printf("reel :%d\n", isprint(is_print));
//	printf("reel :%d\n", isprint(is_print2));
	printf("mine :%d\n", ft_isprint(is_print));
//	printf("mine :%d\n", ft_isprint(is_print2));
	ft_kirby();
	printf(" %s\n", "ft_strnew ----------------------------------");
//	printf("%s\n", ft_strnew(3));
//	printf("%s\n", ft_strnew(8));
//	printf("%s\n", ft_strnew(15));
//	printf("%s\n", ft_strnew(30));
	
	
	
	
	
	
	return(0);
	}
